#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_dialog_actioned_on_disabled_toast = global::App1.Resource.String.mobile_center_distribute_dialog_actioned_on_disabled_toast;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_download_progress_number_format = global::App1.Resource.String.mobile_center_distribute_download_progress_number_format;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_download_successful_notification_message = global::App1.Resource.String.mobile_center_distribute_download_successful_notification_message;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_download_successful_notification_title = global::App1.Resource.String.mobile_center_distribute_download_successful_notification_title;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_downloading_mandatory_update = global::App1.Resource.String.mobile_center_distribute_downloading_mandatory_update;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_install = global::App1.Resource.String.mobile_center_distribute_install;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_unknown_sources_dialog_message = global::App1.Resource.String.mobile_center_distribute_unknown_sources_dialog_message;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_unknown_sources_dialog_settings = global::App1.Resource.String.mobile_center_distribute_unknown_sources_dialog_settings;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_download = global::App1.Resource.String.mobile_center_distribute_update_dialog_download;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_ignore = global::App1.Resource.String.mobile_center_distribute_update_dialog_ignore;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_message = global::App1.Resource.String.mobile_center_distribute_update_dialog_message;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_postpone = global::App1.Resource.String.mobile_center_distribute_update_dialog_postpone;
			global::Microsoft.Azure.Mobile.Distribute.Resource.String.mobile_center_distribute_update_dialog_title = global::App1.Resource.String.mobile_center_distribute_update_dialog_title;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000e
			public const int ApplicationName = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int Hello = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int mobile_center_distribute_dialog_actioned_on_disabled_toast = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int mobile_center_distribute_download_progress_number_format = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int mobile_center_distribute_download_successful_notification_message = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int mobile_center_distribute_download_successful_notification_title = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int mobile_center_distribute_downloading_mandatory_update = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int mobile_center_distribute_install = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int mobile_center_distribute_unknown_sources_dialog_message = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int mobile_center_distribute_unknown_sources_dialog_settings = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int mobile_center_distribute_update_dialog_download = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int mobile_center_distribute_update_dialog_ignore = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int mobile_center_distribute_update_dialog_message = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int mobile_center_distribute_update_dialog_postpone = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int mobile_center_distribute_update_dialog_title = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
